name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '26 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Pip install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        scrapy crawl zonedb -O zonedbraw.jl
        cat zonedbraw.jl | jq -c -s 'sort_by(.domain) |.[]' > zonedb.jl
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add zonedb.jl
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
